sudo: required

services:
  - docker

before_install:
- docker build -t frontend .

script:
- docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) frontend npm install --no-bin-links || npm install --no-bin-links
- docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) -p 3000:3000 -p 3001:3001 frontend gulp dist